 USE Database1_1
 GO

DROP TABLE dbo.Table1
 
IF OBJECT_ID('dbo.Table1') IS NULL
CREATE TABLE dbo.Table1
(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name VARCHAR(30) NOT NULL,
	StartedAt DATETIME NOT NULL,
	MinutesDuration INT NOT NULL
)
GO